apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basic_app.fullname" . }}-private-dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}